# NUMPY ASSIGNMENT
1. Create a 1D array of numbers from 0 to 9.

2. Create a 3×3 numpy array of all True’s

3. Given an array as input, print only odd numbers as output

4. Replace all odd numbers in arr with -2

5. How to reshape an array?

6. Convert a 1D array to a 2D array with 2 rows

7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

8. Given array, check if there are any null values and print them out. 

9. How to replace all missing values with 0 in a numpy array?

10. How to find the count of each unique number in a NumPy array?

11. How to convert a numeric to a categorical (text) array?

12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1. Create a 1D array of numbers from 0 to 9.
oned_array=np.arange(0,10,1)
oned_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 2) Create a 3×3 numpy array of all True’s
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# 3) Given an array as input, print only odd numbers as output
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Array with odd numbers: ",arr1[arr1%2!=0])

Array with odd numbers:  [1 3 5 7 9]


In [5]:
#  4) Replace all odd numbers in above arr with -2
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("original array:",arr1)
print("replacing odd numbers in arr1 with -2:")
arr1[arr1%2!=0]=-2
arr1

original array: [1 2 3 4 5 6 7 8 9]
replacing odd numbers in arr1 with -2:


array([-2,  2, -2,  4, -2,  6, -2,  8, -2])

In [6]:
# 5) How to reshape an array?
# Answer: We can reshape an array using reshape function with new dimensions
a=np.array([[0,1],[2,3],[5,6]])
print(a,a.shape)
a_=a.reshape(2,3)
print("\n\n",a_,a_.shape)

[[0 1]
 [2 3]
 [5 6]] (3, 2)


 [[0 1 2]
 [3 5 6]] (2, 3)


In [10]:
# 6) Convert a 1D array to a 2D array with 2 rows
arr1=np.arange(8)
print("original 1D array")
arr1


original 1D array


array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
print("\n Reshaped 2D array ")
arr2=arr1.reshape(2,4)
arr2


 Reshaped 2D array 


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
# 7) Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.
import numpy as np
a=np.arange(1,10)
print("original array:",a)
b=a[np.where((a%2!=0)|(a%4==0))]
print("modified array:",b)

original array: [1 2 3 4 5 6 7 8 9]
modified array: [1 3 4 5 7 8 9]


In [18]:
# 8) Given array, check if there are any null values and print them out.
a=[0,1,2,3,4,0,0,6,7,8,9]
arr=np.array(a)
print(arr)
print("\n Test whether the array has any null values or not:")
print((~arr.any(axis=0)).any())


[0 1 2 3 4 0 0 6 7 8 9]

 Test whether the array has any null values or not:
False


In [21]:
# 9) How to replace all missing values with 0 in a numpy array?
arr1=np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])
print("Original Array:",arr1)
print("\n Nan values replaced by 0 in the array ")
arr1[np.isnan(arr1)]=0
print(arr1)

Original Array: [[ 1.  2. nan]
 [ 4.  5.  6.]
 [nan  7. nan]]

 Nan values replaced by 0 in the array 
[[1. 2. 0.]
 [4. 5. 6.]
 [0. 7. 0.]]


In [22]:
# 10) How to find the count of each unique number in a NumPy array?
import numpy as np
x=np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x, return_counts=True)
print(np.array((unique, counts)).T)

[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]


In [23]:
#11) How to convert a numeric to a categorical (text) array?

# Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which
# are divisible by both. 
a=np.arange(99,300)
print("original array:\n")
a

original array:



array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 27

In [24]:
m=a[(a%5==0)|(a%7==0)]  # taking out elements divisible by either 5 or 7
m

array([100, 105, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 140,
       145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 175, 180, 182,
       185, 189, 190, 195, 196, 200, 203, 205, 210, 215, 217, 220, 224,
       225, 230, 231, 235, 238, 240, 245, 250, 252, 255, 259, 260, 265,
       266, 270, 273, 275, 280, 285, 287, 290, 294, 295])

In [25]:
q =m[np.where((m%5!=0)|(m%7!=0))]
print(" Final array excluding common elements:\n")
q

 Final array excluding common elements:



array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

OR...another way to solve question 11 is as below:

In [26]:
x=np.arange(99,299)
y = x[np.where(x%5==0) or np.where(x%7==0) ]
print('np.where :',y)

np.where : [100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275
 280 285 290 295]


In [29]:
# Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
arr=np.arange(10)
print("Original array \n")
print(arr)
rev_arr=arr[::-1]
print(" Reversed array \n")
print(rev_arr)

Original array 

[0 1 2 3 4 5 6 7 8 9]
 Reversed array 

[9 8 7 6 5 4 3 2 1 0]
